# Generated by Django 2.2.3 on 2021-01-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dr_form',
            name='line',
            field=models.CharField(default='LINE', max_length=50),
        ),
    ]
